platform :ios, '7.0'

inhibit_all_warnings!

target :KZCollectionViewTableLayoutTests, :exclusive => true do
  pod 'xctest-assert-eventually'
  pod 'OCMock', '~> 2.2'
  pod 'OCHamcrest', '~> 3.0.0'
end
